### ISSUE TITLE
Unable to determine Git repo path

### ISSUE THREAD

**Issue by aristidesfl** [divmain/GitSavvy#726]
I've been getting this error when I try to commit recently. 
I don't know how to reproduce, or what causes the error.
Tried to open/close sublime, with and without project. Nothing seems to help.

**Comment by wldcordeiro** [comment]
Seems fixed in the latest. I came here to report the same.

**Comment by randy3k** [comment]
It should be fixed at 5a90caf901fff732554a548f350eedd1449b8453. Please reopen this if it is not the case.

**Comment by randy3k** [comment]
It might still happen if one changes windows very quickly, #721 is fixing it.

**Comment by harshal-gajare** [comment]
I am getting the same error 

Traceback (most recent call last):
  File "core.commands.commit in /Users/lm97580/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 142, in <lambda>
  File "core.commands.commit in /Users/lm97580/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 162, in run_async
  File "core.git_command in /Users/lm97580/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 109, in git
GitSavvy.core.exceptions.GitSavvyError: Unable to determine Git repo path.

**Comment by aristidesfl** [comment]
Still have it some times.

**Comment by randy3k** [comment]
I can see that it would rarely happen if the view is closed in the middle of the process of https://github.com/divmain/GitSavvy/blob/32463a7013f2a02a5c8e40059ecea0af95a6b72d/core/commands/status_bar.py#L58-L64

An ultimate solution is to put a `disable_offer_init` context manager around this piece of code.

**Comment by randy3k** [comment]
@harshal-gajare 
would you explain how we can reproduce it?

**Comment by harshal-gajare** [comment]
@randy3k  Not sure how to reproduce it. If I remember correctly I think I had the commit window open and then probably closed it without committing and switched windows to something that that might have resulted in this error. Would you like me to look at some other logs and submit them ?

**Comment by XIAOLONGLII** [comment]
I have the same error

**Comment by randy3k** [comment]
Could you provide some reproducible steps?

**Comment by mp-17** [comment]
I have the same problem. I modified the settings and added the correct path for git, but if I try to execute a command the system does nothing.

**Comment by agiantfreakingsteak** [comment]
This seems to occur for me when I go to the command palette (shift + Cmd + P on Mac) and try to go to Git:Branch

After doing this, nothing happens and the console outputs:
File "/Users/lucas/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 429, in get_repo_path
ValueError: Unable to determine Git repo path.

**Comment by stoivo** [comment]
@agiantfreakingsteak could you open a new issue where you add as much details as you can.

Specify versions and steps to reproduce. More details is better.
